version: '3.8'

services:
  db:
    image: postgres:15
    init: true
    ports:
      - "55432:5432"
    volumes:
      - database:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/data/pg_hba.conf
    env_file:
      - .env

  web:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  database:
