"""initial migration

Revision ID: 71d501fcb62e
Revises: 
Create Date: 2025-05-01 09:22:12.248231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d501fcb62e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('meal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.Enum('Завтрак', 'Обед', 'Ужин', 'Перекус', name='meal_types'), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('time', sa.Time(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('body_type', sa.Enum('Эктоморф', 'Мезоморф', 'Эндоморф', name='body_types'), nullable=False),
    sa.Column('gender', sa.Enum('Мужской', 'Женский', name='genders'), nullable=False),
    sa.Column('nutrition_purpose', sa.Enum('Потеря веса', 'Набор веса', 'Лечебное', name='nutrition_purposes'), nullable=False),
    sa.Column('allergies', sa.String(length=200), nullable=True),
    sa.Column('food_preferences', sa.String(length=200), nullable=True),
    sa.Column('lifestyle', sa.Enum('Малоактивный', '1-2 тренировки в неделю', '3-4 тренировки в неделю', '5-7 тренировок в неделю', name='lifestyles'), nullable=True),
    sa.Column('dietary_restrictions', sa.String(length=200), nullable=True),
    sa.Column('sleep', sa.Enum('4-5 часа', '5-7 часа', '8-10 часа', name='sleeps'), nullable=True),
    sa.Column('available_products', sa.String(length=300), nullable=True),
    sa.Column('wishes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meal_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('proteins', sa.Integer(), nullable=False),
    sa.Column('fats', sa.Integer(), nullable=False),
    sa.Column('carbs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meal.id'], name='fk_product_meal_id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('user_profile')
    op.drop_table('meal')
    op.drop_table('user')
    op.drop_table('token')
    # ### end Alembic commands ###
