"""token jti is db.text

Revision ID: 85474a7002ba
Revises: 7270847d8a99
Create Date: 2025-05-03 05:42:24.405438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85474a7002ba'
down_revision = '7270847d8a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.alter_column('jti',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token', schema=None) as batch_op:
        batch_op.alter_column('jti',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
