"""completed moved from product to meal

Revision ID: 8a046868c00e
Revises: 8da6accae1bb
Create Date: 2025-05-01 02:41:46.510731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a046868c00e'
down_revision = '8da6accae1bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.Boolean(), server_default=sa.text('0'), nullable=True))

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed', sa.BOOLEAN(), nullable=True))

    with op.batch_alter_table('meal', schema=None) as batch_op:
        batch_op.drop_column('completed')

    # ### end Alembic commands ###
