"""empty message

Revision ID: 8da6accae1bb
Revises: 973d84a48ec1
Create Date: 2025-04-29 08:09:51.215257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8da6accae1bb'
down_revision = '973d84a48ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutrition_purpose', sa.Enum('Потеря веса', 'Набор веса', 'Лечебное', name='nutrition_purposes'), nullable=False))
        batch_op.drop_column('nutrition_goal')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutrition_goal', sa.VARCHAR(length=11), nullable=False))
        batch_op.drop_column('nutrition_purpose')

    # ### end Alembic commands ###
