"""empty message

Revision ID: 973d84a48ec1
Revises: 889cb0bf71ab
Create Date: 2025-04-29 05:07:45.658083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '973d84a48ec1'
down_revision = '889cb0bf71ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meal_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_product_meal_id', 'meal', ['meal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_meal_id', type_='foreignkey')
        batch_op.drop_column('meal_id')

    # ### end Alembic commands ###
